name: Shadow
version: '${project.version}'
main: uk.co.tmdavies.shadow.Shadow
api-version: 1.19
commands:
  shadow:
    description: Main Command
  item:
    description: Item Command
  dump:
    description: Dump Command
permissions:
  shadow.admin:
    default: op
  shadow.admin.item:
    default: op